name: Generate Sitemap

on:
  push:
    branches: [ main, master ]  # شاخه اصلی رو وارد کن
  pull_request:
    branches: [ main, master ]

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Create sitemap generator script
        run: |
          cat > generate-sitemap.js << 'EOF'
          const fs = require('fs');
          const path = require('path');
          const glob = require('glob');

          // پیدا کردن تمام فایل‌های HTML در ریشه و زیرپوشه‌ها
          const htmlFiles = glob.sync('**/*.html', {
            ignore: 'node_modules/**',
            nodir: true
          });

          const baseUrl = 'https://www.dash-smal.ir';
          const today = new Date().toISOString().split('T')[0];

          let sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
        http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">\n\n`;

          htmlFiles.forEach(file => {
            const url = file === 'index.html' ? '/' : '/' + file;
            const fullUrl = baseUrl + url;
            const priority = url === '/' ? '1.0' : '0.8';
            const changefreq = url === '/' ? 'weekly' : 'monthly';

            sitemap += `  <url>
    <loc>${fullUrl}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority}</priority>
  </url>\n\n`;
          });

          sitemap += '</urlset>';

          // ذخیره فایل
          fs.writeFileSync('sitemap.xml', sitemap, 'utf8');
          console.log('✅ sitemap.xml با موفقیت ساخته شد.');
          EOF

      - name: Install dependencies
        run: npm install glob

      - name: Generate sitemap.xml
        run: node generate-sitemap.js

      - name: Commit and push if changed
        run: |
          git config user.name "Sitemap Bot"
          git config user.email "bot@dash-smal.ir"
          git add sitemap.xml
          git diff --quiet && git diff --staged --quiet || (git commit -m "🤖 Auto-update sitemap.xml" && git push)